version: "3.9"

services:
  app:
    build: .
    container_name: sports_shop
    restart: unless-stopped
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    ports:
      - "${APP_PORT:-8000}:8000"
    stdin_open: true
    tty: true
    command: uvicorn sports_shop.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - db
    networks:
      - sports_shop_network

  db:
    image: postgres:15-alpine
    container_name: sports_shop_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-sports_shop}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - sports_shop_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-sports_shop}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
    driver: local

networks:
  sports_shop_network:
    driver: bridge
