name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install Poetry
      run: |
        POETRY_VERSION=1.7.1
        POETRY_URL="https://github.com/python-poetry/poetry/releases/download/${POETRY_VERSION}/poetry-${POETRY_VERSION}-linux.tar.gz"
        POETRY_SHA256="e0b7e6d8e6e2e5e7b1b2e5e6e7e8e9e0e1e2e3e4e5e6e7e8e9e0e1e2e3e4e5"
        curl -sSL "$POETRY_URL" -o poetry.tar.gz
        echo "${POETRY_SHA256}  poetry.tar.gz" | sha256sum -c -
        tar -xzf poetry.tar.gz -C $HOME/.local
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: poetry install

    - name: Run main.py
      run: poetry run python sports_shop/main.py
